(define symbol-length
  	(lambda (inSym)
	  	(if (symbol? inSym)
		  	(string-length (symbol->string inSym))
				0
		)
	)
)
(define sequence?
  	(lambda (inSeq)
	  (if (list? inSeq)
	    	(if (null? inSeq) #t (if (= 1 (symbol-length (car inSeq))) (sequence? (cdr inSeq)) #f))
		#f
		)
	)
)
(define same-sequence?
  	(lambda (inSeq1 inSeq2)
	  (if (sequence? inSeq1) 
	    (if (sequence? inSeq2)
	      (if (null? inSeq1) 
		(if (null? inSeq2) #t #f)
		(if (null? inSeq2) #f (if (eq? (car inSeq1) (car inSeq2)) (same-sequence? (cdr inSeq1) (cdr inSeq2)) #f)))
	    (error "inSeq2 is not a sequence")) 
	  (error "inSeq1 is not a sequence"))
	 )
)
(define reverse-sequence
  	(lambda (inSeq)
	  (if (sequence? inSeq) 
	    (if (null? inSeq) '() (append (reverse-sequence (cdr inSeq)) (list (car inSeq)))) 
	    (error "inSeq is not a sequence")
	    )
	 )
)
(define palindrome?
  	(lambda (inSeq)
	  (if (sequence? inSeq) 
	    (if (null? inSeq) #t (if (same-sequence? inSeq (reverse-sequence inSeq)) #t #f)) 
	    (error "inSeq is not a sequence"))
	 )
	
)
(define member?
  	(lambda (inSym inSeq)
	  (if (sequence? inSeq) 
	    (if (symbol? inSym) 
	      (if (null? inSeq) #f (if (eq? inSym (car inSeq)) #t (member? inSym (cdr inSeq))))
	      (error "inSym is not a symbol")) 
	    (error "inSeq is not a sequence"))
	  )
)
(define remove-member
  	(lambda (inSym inSeq)
	  (if (and (symbol? inSym) (sequence? inSeq) (member? inSym inSeq)) 
	    (if (eq? inSym (car inSeq)) (cdr inSeq) (cons (car inSeq) (remove-member inSym (cdr inSeq))))
	    (error "invalid input"))
	  )
)
(define anagram?
  	(lambda (inSeq1 inSeq2)
	  (if (and (sequence? inSeq1) (sequence? inSeq2))
	    (if (null? inSeq2) 
	      (if (null? inSeq1) #t #f)
	    (if (member? (car inSeq2) inSeq1) (anagram? (remove-member (car inSeq2) inSeq1) (cdr inSeq2)) #f))
	    (error "invalid input"))
	 )
)
(define anapoli?
  	(lambda (inSeq1 inSeq2)
	  (if (and (sequence? inSeq1) (sequence? inSeq2))
		  ( if (palindrome? inSeq2) (if (anagram? inSeq1 inSeq2) #t #f) #f)
		  (error "input is not a sequence"))
	  )
)
